// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNut7C9kaoAiKAXXGnr6O0l0A4VpVUheo',
    appId: '1:195328053625:web:25fd3f5e0e69398a6b9fa8',
    messagingSenderId: '195328053625',
    projectId: 'fuelapp-76dd0',
    authDomain: 'fuelapp-76dd0.firebaseapp.com',
    storageBucket: 'fuelapp-76dd0.appspot.com',
    measurementId: 'G-193RTRYFE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1-llJqeqcA86zlQr7AfEfyfxdYju43o',
    appId: '1:195328053625:android:9cf55fe270a124086b9fa8',
    messagingSenderId: '195328053625',
    projectId: 'fuelapp-76dd0',
    storageBucket: 'fuelapp-76dd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBY7-1b7gP_xyQWc8XkBAEHEgQDtIRZd0',
    appId: '1:195328053625:ios:5c329f58cf04a2396b9fa8',
    messagingSenderId: '195328053625',
    projectId: 'fuelapp-76dd0',
    storageBucket: 'fuelapp-76dd0.appspot.com',
    iosBundleId: 'com.example.fuelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBY7-1b7gP_xyQWc8XkBAEHEgQDtIRZd0',
    appId: '1:195328053625:ios:92a45426a173ca0b6b9fa8',
    messagingSenderId: '195328053625',
    projectId: 'fuelapp-76dd0',
    storageBucket: 'fuelapp-76dd0.appspot.com',
    iosBundleId: 'com.example.fuelapp.RunnerTests',
  );
}
